### PR TITLE
Gamerules

### PR DESCRIPTION
**Pull request by Defman**
Do we want to store gamerules as just fields or do want to store them as a kind of `Set` or `&[u8]`?

### CODE REVIEW

**Comment by InfinityZ25** [comment]
Store them as sets. It's neater and the difference in memory is not too great.

**Comment by Defman** [comment]
I dropped the idea of using new types and instead used a single struct with fields as the rules.

**Comment by caelunshun** [comment]
@Defman is this ready for merging?

**Comment by Defman** [comment]
Yes and no, missing serialization and deserialization.

**Comment by Defman** [comment]
@caelunshun Lets merge it and ill submit a separate PR for saving and loading.

**Review by caelunshun — APPROVED** [review]

**Pull request merged**
