### PR TITLE
Handle placing blocks with cardinality

### PR DESCRIPTION
**Pull request by ssttevee**
The logic for determining cardinality feels like it doesn't belong there. Where do you think it should live?

Also, for the code in `categories.rs`, should those be part of the generated code? I could extend the generator to generate `has_x` functions.

Side note: I'd like to work towards working redstone; should I submit many small PRs or fewer big ones?

### CODE REVIEW

**Comment by ssttevee** [comment]
I just realized #241 addresses this 👀

**Comment by amberkowalski** [comment]
I can merge this into the pr with your permission, since I have changed how block placement works programmatically but haven't implemented cardinality.

**Comment by ssttevee** [comment]
That sounds good, but I think I should include all the cardinalities (down + cubic) first as well as figure out the situation with the categories.

**Comment by amberkowalski** [comment]
If you want I think you can open prs on my development fork and I can merge them in whenever you get that done, thanks for working on this :)

**Comment by ssttevee** [comment]
merged into #241

**Pull request closed without merging**
