### PR TITLE
reverse the hashmap in codegen

### PR DESCRIPTION
**Pull request by PonasKovas**
I was just skimming through the source and thought I would do this as my first PR haha

### CODE REVIEW

**Comment by caelunshun** [comment]
Looks like rustfmt failed on CI, make sure to run `cargo fmt`.

**Comment by PonasKovas** [comment]
Oh man what did I mess up this time? `cargo test` passes all the tests on my machine

**Comment by caelunshun** [comment]
Sorry about that, CI failed spuriously :) I'll rerun it.

**Comment by PonasKovas** [comment]
I probably shouldn't have committed the Cargo.lock changes. Could it be that this is the problem?

**Comment by caelunshun** [comment]
It's possible, yes. Try running `cargo update` and then committing that change.

**Comment by PonasKovas** [comment]
Using `cargo update` makes the situation even worse. I'll try to just reverse the cargo.lock changes

**Comment by PonasKovas** [comment]
Science can not explain this.

**Comment by PonasKovas** [comment]
I think that there's no reason to wait for the CI to work, since the change is very small and easy, and I can confirm that it compiles on my machine.

**Comment by Defman** [comment]
That...’s not how it works, there can be several reasons why it may only compile on your machine, but not others. To name a few : compiler version, operating system, and or available dlibs.

**Comment by PonasKovas** [comment]
So.. You're just gonna wait until someone fixes CI, even though this is a very minor change and can be confirmed manually?

**Comment by caelunshun** [comment]
Sorry, I forgot about this. Will merge :)

**Pull request merged**
