### PR TITLE
Fix lethal damage edge case

### PR DESCRIPTION
**Pull request by OmaMitStaubsauger**
I noticed two issues with the damage logic:
- an entity is only killed when the damage exceeds it's health, but not if it reaches exactly zero, while it should be considered dead at that point (I assume from the fact that the client shows the death screen at zero health, correct me if I'm wrong here) 
- when changing the threshold to less than one and reaching exactly zero health, the entities health is not updated to the new value before killing (which causes the client not to show a death screen )

EDIT: the second issue of course only occurred when fixing the first

### CODE REVIEW

**Comment by OmaMitStaubsauger** [comment]
sorry, I noticed that I completely forgot to actually update the health component. I will fix it and write some tests :)

**Review by caelunshun — APPROVED** [review]
Thanks, looks good to me.

**Comment by caelunshun** [comment]
Looks like there's a compile error from the borrow checker, at least on CI.

**Comment by OmaMitStaubsauger** [comment]
Oh, I forgot to push the newest changes. I was also working on some test cases, but I'm struggling with the unit testing framework, so I can't include any for now.

I rebased on develop and checked `clippy` and `rustfmt` this time, but there are new changes unrelated to mine that broke the checks

**Comment by caelunshun** [comment]
Thanks!

**Pull request merged**
