### PR TITLE
Remove plugin test file and fix clippy error

### PR DESCRIPTION
**Pull request by kirawi**
# Remove plugin test file and fix clippy error

## Status

- [x] Ready 

## Checklist

- [x] Ran `cargo fmt`, `cargo clippy`, `cargo build --release` and `cargo test` and fixed any generated errors!
- [x] Removed unnecessary commented out code
- [x] Used specific traces (if you trace actions please specify the cause i.e. the player)

### CODE REVIEW

**Comment by amberkowalski** [comment]
Whats with the `wip`?

**Comment by kirawi** [comment]
Accidentally mixed up branches. Also, I don't know why the build failed.

**Comment by kirawi** [comment]
I'm very confused, why is it only happening now? #407 doesn't have this problem.

**Comment by caelunshun** [comment]
It's likely caused by a recent Rust update adding new clippy lints. It should be fine to fix them as a part of this PR, or alternatively we can merge and fix in a separate PR.

**Comment by kirawi** [comment]
Ready for review.

**Review by caelunshun — APPROVED** [review]
Thanks!

**Pull request merged**
