### PR TITLE
Minimal bow holding time for shooting

### PR DESCRIPTION
**Pull request by PonasKovas**
Discussed in #303

### CODE REVIEW

**Comment by PonasKovas** [comment]
Oops looks like some older commits from a previous PR are included in this one too. Will git handle it well? I can create a new clean PR if needed

**Comment by Defman** [comment]
Just hard reset the un related file.

**Comment by amberkowalski** [comment]
You can rebase the good commits onto `develop`, then force push. That should fix the history.

**Comment by PonasKovas** [comment]
I'll just create a new PR

**Pull request closed without merging**
